// How the sidecar learns who it is. Everything arrives through the environment
// rather than argv: argv is world-readable via `ps`, and the token must not be.

/** Fixed port + token for `bun --watch` during development. */
export const DEV_PORT = 51789;
export const DEV_TOKEN = 'lore-dev-token';

export interface Config {
    dev: boolean;
    /** Exit when this pid disappears; see `watchParent`. */
    parentPid: null | number;
    /** 0 means "pick an ephemeral port", which is what production does. */
    port: number;
    /** Bearer token every request must carry. */
    token: string;
    /** Vault to open on boot, if the host already knows it. */
    vault: null | string;
}

export function loadConfig(env: Record<string, string | undefined> = Bun.env): Config {
    const token = env.LORE_TOKEN;
    const dev = !token;

    return {
        dev,
        parentPid: env.LORE_PARENT_PID ? Number(env.LORE_PARENT_PID) : null,
        port: env.LORE_PORT ? Number(env.LORE_PORT) : dev ? DEV_PORT : 0,
        // Only development is allowed to fall back to a known token — production
        // always gets one generated by the host.
        token: token ?? DEV_TOKEN,
        vault: env.LORE_VAULT || null,
    };
}

/**
 * The line the host reads from stdout to discover the port. It is the whole
 * handshake, so it must be exactly one line and the first thing we print.
 */
export const HANDSHAKE_PREFIX = 'LORE_SIDECAR';

export function handshakeLine(port: number): string {
    return `${HANDSHAKE_PREFIX} ${JSON.stringify({ pid: process.pid, port })}`;
}

/**
 * Exits when the host process disappears.
 *
 * Tauri kills the sidecar on a clean shutdown, but a SIGKILL of the app (Force
 * Quit, a crash, a debugger stop) never runs that path and would strand this
 * process holding the vault. Polling the parent is the only portable way to
 * notice, since the OS reparents us to init rather than signalling.
 */
export function watchParent(parentPid: null | number, intervalMs = 5000): null | Timer {
    if (!parentPid) return null;
    return setInterval(() => {
        try {
            // Signal 0 checks for existence without delivering anything.
            process.kill(parentPid, 0);
        } catch {
            process.exit(0);
        }
    }, intervalMs);
}
